// =============================
// 1) LISTE DES QUIZZ
// =============================
const allQuizzes = [
  [
    //Quizz 1
    {
      text: "Combien de couches comporte le modèle OSI ?",
      type: "single",
      choices: ["3", "5", "7", "9"],
      correct: 2,
    },
    {
      text: "Quelle est la couche la plus basse du modèle OSI ?",
      type: "single",
      choices: ["Physique", "Transport", "Réseau", "Session"],
      correct: 0,
    },
    {
      text: "La couche transport est la couche numéro :",
      type: "single",
      choices: ["2", "4", "5", "6"],
      correct: 1,
    },
    {
      text: "Quelle couche gère l'adresse IP ?",
      type: "single",
      choices: ["Physique", "Liaison de données", "Réseau", "Transport"],
      correct: 2,
    },
    {
      text: "Vrai ou faux : La couche application correspond à l'interface directe avec l'utilisateur.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "Quel protocole fonctionne principalement à la couche 3",
      type: "single",
      choices: ["HTTP", "IP", "TCP", "FTP"],
      correct: 1,
    },
    {
      text: "La couche session sert à :",
      type: "single",
      choices: [
        "Transporter les paquets",
        "Établir, gérer et terminer des sessions",
        "Gérer l'accès au support physiques",
        "Assurer le chiffrement des données",
      ],
      correct: 2,
    },
    {
      text: "À quelle couche se situe le protocole TCP ?",
      type: "single",
      choices: ["Application", "Transport", "Réseau", "Présentation"],
      correct: 1,
    },
    {
      text: "La couche liaison de données s’occupe principalement de :",
      type: "single",
      choices: [
        "La présentation des données",
        "L’établissement de la session",
        "L’accès au support physique et aux adresses MAC",
        "L’encapsulation dans des paquets",
      ],
      correct: 2,
    },
    {
      text: "Vrai ou Faux : La couche physique détermine la manière dont les signaux sont transmis (électrique, radio, fibre, etc.).",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "Quel protocole fonctionne à la couche application ?",
      type: "single",
      choices: ["HTTP", "UDP", "IP", "ARP"],
      correct: 0,
    },
    {
      text: "La couche présentation s'occupe de :",
      type: "single",
      choices: [
        "Gérer les erreurs",
        "Convertir et formater les données",
        "Contrôler le flux",
        "Envoyer des bits",
      ],
      correct: 1,
    },
    {
      text: "Vrai ou Faux : Le protocole ARP fonctionne à la couche application.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 1,
    },
    {
      text: "A quelle couche correspond une carte réseau (NIC) ?",
      type: "single",
      choices: ["Physique et liaison de données", "Application", "Transport", "Session"],
      correct: 0,
    },
    {
      text: "Vrai ou Faux : L’encapsulation se produit lorsque chaque couche ajoute ses propres informations d’en-tête.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "Quel est le PDU (unité de données de protocole) de la couche transport ?",
      type: "single",
      choices: ["Bit", "Trame", "Segment", "Paquet"],
      correct: 2,
    },
    {
      text: "Vrai ou Faux : Un switch travaille principalement à la couche liaison de données.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "La segmentation des messages en petits morceaux est gérer par :",
      type: "single",
      choices: [
        "La couche réseau",
        "La couche transport",
        "La couche session",
        "La couche liaison de données",
      ],
      correct: 1,
    },
    {
      text: "Quel protocole fonctionne sans connexion préalable (non connecté) ?",
      type: "single",
      choices: ["TCP", "UDP", "HTTP", "IP"],
      correct: 1,
    },
    {
      text: "Vrai ou faux : La couche application assure la livraison des données.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 1,
    },
  ],
  //Quizz 2
  [
    {
      text: "Lors de l’encapsulation, chaque couche ajoute :",
      type: "single",
      choices: ["un en-tête", "Un pied de page uniquement", "Une compression", "Une adresse MAC"],
      correct: 0,
    },
    {
      text: "Vrai ou Faux : L'encapsulation commence à la couche physique.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 1,
    },
    {
      text: "Quel est le bon ordre des unités de données (PDU) lors de l'envoi ?",
      type: "single",
      choices: [
        "Bit → Trame → Segment → Paquet → Donnée",
        "Donnée → Segment → Paquet → Trame → Bit",
        "Trame → Paquet → Segment → Donnée → Bit",
        "Bit → Segment → Trame → Paquet → Donnée",
      ],
      correct: 1,
    },
    {
      text: "Quel PDU est associé à la couche liaison de données ?",
      type: "single",
      choices: ["Bit", "Trame", "Segment", "Paquet"],
      correct: 1,
    },
    {
      text: "Vrai ou faux : Lors de la désencapsulation, les en-têtes sont supprimés couche par couche.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "A quelle couche correspond le segment ?",
      type: "single",
      choices: ["Physique", "Liaison de données", "Réseau", "Transport"],
      correct: 3,
    },
    {
      text: "L'adresse MAC se touve dans quelle couche ?",
      type: "single",
      choices: ["Physique", "Liaison de données", "Réseau", "Transport"],
      correct: 2,
    },
    {
      text: "Vrai ou faux : L'encapsulation se produit uniquement à l'envoi des données.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 1,
    },
    {
      text: "Quelles informations sont ajoutées dans l'en-tête de la couche transport ? ",
      type: "single",
      choices: ["Adresse MAC", "Adresse IP", "Port source et port de destination", "Type de média"],
      correct: 2,
    },
    {
      text: "Vrai ou faux : Le portocole ARP sert à trouver une adresse MAC à partir d'une adresse IP.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "Que contient l'en-tête d'un paquet IP ?",
      type: "single",
      choices: [
        "Port source et port de destination",
        "Adresse MAC",
        "Adresse IP source et destination",
        "Type de média",
      ],
      correct: 2,
    },
    {
      text: "Vrai ou faux : L'encapsulation aide à organiser et à guider les données vers leur bonne destination.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "Lors de la désencapsulation, que fait la couche réseau ?",
      type: "single",
      choices: [
        "Elle vérifie les ports",
        "Elle vérifie les adresses IP",
        "Elle vérifie les adresses MAC",
        "Elle ne fait rien",
      ],
      correct: 1,
    },
    {
      text: "Quel protocole fonctionne à la couche transport ?",
      type: "single",
      choices: ["IP", "TCP", "ARP", "DNS"],
      correct: 1,
    },
    {
      text: "Vrai ou faux : L'unité de données de la couche physique est la trame.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 1,
    },
    {
      text: "Vrai ou faux : Lorsqu'on désencapsule un message, on récupère la donnée initiale après avoir retirer chaque en-tête.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "Quelle couche vérifie l'intégrité des données et la bonne réception ?",
      type: "single",
      choices: ["Liaison de données", "Réseau", "Transport", "Application"],
      correct: 2,
    },

    {
      text: "Quel est le PDU de la couche application",
      type: "single",
      choices: ["Paquet", "Segment", "Trame", "Donnée"],
      correct: 3,
    },
    {
      text: "Vrai ou faux : Un routeur travaille principalement avec les paquet IP",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "Vrai ou faux : Le processus d'encapsulation est inversé lors de la réception des données.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
  ],
  //Quizz 3
  [
    {
      text: "Vrai ou Faux : Un switch fonctionne principalement à la couche réseau.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 1,
    },
    {
      text: "À quelle couche fonctionne le protocole HTTPS ?",
      type: "single",
      choices: ["Application", "Transport", "Réseau", "Liaison de données"],
      correct: 0,
    },
    {
      text: "Vrai ou Faux : Une adresse IP identifie un appareil sur un réseau mondial",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "Quel équipement utilise des adresses MAC pour transmettre les données ?",
      type: "single",
      choices: ["Switch", "Routeur", "Modem", "Serveur"],
      correct: 0,
    },
    {
      text: "Vrai ou Faux : Un routeur travail uniquement avec des trames.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 1,
    },
    {
      text: "Quelle couche garantit que les paquets sont correctement livrés, dans le bon ordre et sans erreur ?",
      type: "single",
      choices: ["Application", "Transport", "Réseau", "Liaison de données"],
      correct: 1,
    },
    {
      text: "Vrai ou Faux : L'adresse MAC peut changer à chaque connexion Internet.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 1,
    },
    {
      text: "Quel protocole permet de tansférer des fichiers à distance ?",
      type: "single",
      choices: ["HTTP", "FTP", "TCP", "UDP"],
      correct: 1,
    },
    {
      text: "Vrai ou Faux : L'adresse IP d'un appareil change toujours lorsqu'il change de réseau.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "Que fait le protocole ARP ?",
      type: "single",
      choices: [
        "Trouve une adresse IP à partir d'une adresse MAC",
        "Trouve une adresse MAC à partir d'une adresse IP",
        "Contrôle les sessions",
        "Gère le chiffrement",
      ],
      correct: 1,
    },
    {
      text: "Vrai ou Faux : Le protocole DNS permet de résoudre les noms de domaine en adresses IP",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "Quel équipement connecte plusieurs réseaux différents ?",
      type: "single",
      choices: ["Switch", "Hub", "Routeur", "Câble réseau"],
      correct: 2,
    },
    {
      text: "Vrai ou Faux : La couche transport utilise des numéros de ports pour identifier les applications.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "Quel port est utilisé par le protocole HTTPS ?",
      type: "single",
      choices: ["80", "21", "443", "53"],
      correct: 0,
    },
    {
      text: "Vrai ou Faux : UDP garantit la livraison des données.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 1,
    },
    {
      text: "À quelle couche apparatient l'adresse IP ?",
      type: "single",
      choices: ["Liaison de données", "Réseau", "Transport", "Physique"],
      correct: 1,
    },
    {
      text: "Vrai ou Faux : Si un câble réseau est défectueux, la couche physique est concernée.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "À quelle couche fonctionne le TCP ?",
      type: "single",
      choices: ["Application", "Transport", "Réseau", "Liaison de données"],
      correct: 1,
    },
    {
      text: "Vrai ou Faux : Un serveur Web fonctionne à la couche application.",
      type: "single",
      choices: ["Vrai", "Faux"],
      correct: 0,
    },
    {
      text: "Quel protocole permet de résoudre les noms de domaine en adresses IP ?",
      type: "single",
      choices: ["FTP", "UDP", "TCP", "DNS"],
      correct: 3,
    },
  ],
];
